// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEntry = `-- name: CreateAuditEntry :execrows
INSERT INTO audit_entries (tenant_id, actor_id, actor_name, actor_email, source, action,
                           document_id, document_title, target_type, target_id, target, role, changed_fields)
SELECT app_tenant_id(), u.id, COALESCE(u.display_name, ''), COALESCE(u.email, ''), $1::text, $2::text,
       d.id, d.title, $3::text, $4::text, $5::text,
       $6::text, $7::text[]
FROM (SELECT 1) one
LEFT JOIN users u ON u.id = $8::uuid
LEFT JOIN documents d ON d.id = $9::uuid
WHERE $9::uuid IS NULL OR d.id IS NOT NULL
`

type CreateAuditEntryParams struct {
	Source        string
	Action        string
	TargetType    string
	TargetID      string
	Target        string
	Role          string
	ChangedFields []string
	ActorID       pgtype.UUID
	DocumentID    pgtype.UUID
}

// Copies the actor's name and email and the document's title so the entry
// outlives both. A document id that matches nothing inserts nothing.
func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAuditEntry,
		arg.Source,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Target,
		arg.Role,
		arg.ChangedFields,
		arg.ActorID,
		arg.DocumentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditByDocument = `-- name: ListAuditByDocument :many
SELECT id, tenant_id, actor_id, actor_email, action, document_id, document_title, target, role, at, actor_name, source, target_type, target_id, changed_fields FROM audit_entries WHERE document_id = $1 ORDER BY id DESC LIMIT 200
`

// ponytail: PRD-0004 reads for SharingRepo.Audit; the AuditRepo queries replace them.
func (q *Queries) ListAuditByDocument(ctx context.Context, documentID pgtype.UUID) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.DocumentID,
			&i.DocumentTitle,
			&i.Target,
			&i.Role,
			&i.At,
			&i.ActorName,
			&i.Source,
			&i.TargetType,
			&i.TargetID,
			&i.ChangedFields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTenant = `-- name: ListAuditByTenant :many
SELECT id, tenant_id, actor_id, actor_email, action, document_id, document_title, target, role, at, actor_name, source, target_type, target_id, changed_fields FROM audit_entries WHERE tenant_id = $1 ORDER BY id DESC LIMIT 500
`

func (q *Queries) ListAuditByTenant(ctx context.Context, tenantID uuid.UUID) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.DocumentID,
			&i.DocumentTitle,
			&i.Target,
			&i.Role,
			&i.At,
			&i.ActorName,
			&i.Source,
			&i.TargetType,
			&i.TargetID,
			&i.ChangedFields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
