// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditSnapshot = `-- name: AuditSnapshot :one
SELECT COALESCE(u.display_name, '')::text AS actor_name, COALESCE(u.email, '')::text AS actor_email,
       d.title AS document_title
FROM (SELECT 1) one
LEFT JOIN users u ON u.id = $1::uuid
LEFT JOIN documents d ON d.id = $2::uuid
WHERE ($2::uuid IS NULL OR d.id IS NOT NULL)
  AND ($1::uuid IS NULL OR u.id IS NOT NULL)
`

type AuditSnapshotParams struct {
	ActorID    pgtype.UUID
	DocumentID pgtype.UUID
}

type AuditSnapshotRow struct {
	ActorName     string
	ActorEmail    string
	DocumentTitle pgtype.Text
}

// Names copied into the audit message so the entry outlives the actor and the
// document (FR-12). An id that matches nothing returns no row (ErrNotFound).
func (q *Queries) AuditSnapshot(ctx context.Context, arg AuditSnapshotParams) (AuditSnapshotRow, error) {
	row := q.db.QueryRow(ctx, auditSnapshot, arg.ActorID, arg.DocumentID)
	var i AuditSnapshotRow
	err := row.Scan(&i.ActorName, &i.ActorEmail, &i.DocumentTitle)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, tenant_id, actor_id, actor_email, action, document_id, document_title, target, role, at, actor_name, source, target_type, target_id, changed_fields, outbox_id FROM audit_entries
WHERE ($1::uuid IS NULL OR actor_id = $1::uuid)
  AND ($2::uuid IS NULL OR document_id = $2::uuid)
  AND ($3::text IS NULL OR action = $3::text)
  AND ($4::timestamptz IS NULL OR at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR at < $5::timestamptz)
  AND ($6::uuid IS NULL OR document_id IN (SELECT id FROM documents WHERE owner_id = $6::uuid))
  AND ($7::bigint IS NULL OR id < $7::bigint)
ORDER BY id DESC
LIMIT $8
`

type ListAuditParams struct {
	ActorID    pgtype.UUID
	DocumentID pgtype.UUID
	Action     pgtype.Text
	FromAt     pgtype.Timestamptz
	ToAt       pgtype.Timestamptz
	OwnerID    pgtype.UUID
	Before     pgtype.Int8
	Lim        int32
}

// Newest first; RLS scopes the tenant. owner_id limits to documents the user owns now (FR-6).
// ponytail: one query with optional filters; AuditRepo.List pins a custom plan (a generic one seq-scans). Split per shape if custom plans ever miss the indexes (NFR-3).
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.ActorID,
		arg.DocumentID,
		arg.Action,
		arg.FromAt,
		arg.ToAt,
		arg.OwnerID,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.DocumentID,
			&i.DocumentTitle,
			&i.Target,
			&i.Role,
			&i.At,
			&i.ActorName,
			&i.Source,
			&i.TargetType,
			&i.TargetID,
			&i.ChangedFields,
			&i.OutboxID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditActors = `-- name: ListAuditActors :many
SELECT actor_id, actor_name, actor_email FROM (
    SELECT DISTINCT ON (actor_id) actor_id, actor_name, actor_email FROM audit_entries
    WHERE actor_id IS NOT NULL
      AND ($1::uuid IS NULL OR document_id IN (SELECT id FROM documents WHERE owner_id = $1::uuid))
    ORDER BY actor_id, id DESC
) s ORDER BY actor_name, actor_email
`

type ListAuditActorsRow struct {
	ActorID    pgtype.UUID
	ActorName  string
	ActorEmail string
}

// ponytail: DISTINCT over visible entries; cache or a summary table if pickers get slow on huge tenants.
func (q *Queries) ListAuditActors(ctx context.Context, ownerID pgtype.UUID) ([]ListAuditActorsRow, error) {
	rows, err := q.db.Query(ctx, listAuditActors, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditActorsRow
	for rows.Next() {
		var i ListAuditActorsRow
		if err := rows.Scan(&i.ActorID, &i.ActorName, &i.ActorEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditDocuments = `-- name: ListAuditDocuments :many
SELECT document_id, document_title FROM (
    SELECT DISTINCT ON (document_id) document_id, document_title FROM audit_entries
    WHERE document_id IS NOT NULL
      AND ($1::uuid IS NULL OR document_id IN (SELECT id FROM documents WHERE owner_id = $1::uuid))
    ORDER BY document_id, id DESC
) s ORDER BY document_title
`

type ListAuditDocumentsRow struct {
	DocumentID    pgtype.UUID
	DocumentTitle pgtype.Text
}

// Latest known title per document, including deleted ones (FR-12).
func (q *Queries) ListAuditDocuments(ctx context.Context, ownerID pgtype.UUID) ([]ListAuditDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listAuditDocuments, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditDocumentsRow
	for rows.Next() {
		var i ListAuditDocumentsRow
		if err := rows.Scan(&i.DocumentID, &i.DocumentTitle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeAuditEntry = `-- name: StoreAuditEntry :exec
INSERT INTO audit_entries (tenant_id, actor_id, actor_name, actor_email, source, action, document_id,
                           document_title, target_type, target_id, target, role, changed_fields, at, outbox_id)
VALUES (app_tenant_id(), $1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12, $13,
        $14)
ON CONFLICT (outbox_id) DO NOTHING
`

type StoreAuditEntryParams struct {
	ActorID       pgtype.UUID
	ActorName     string
	ActorEmail    string
	Source        string
	Action        string
	DocumentID    pgtype.UUID
	DocumentTitle pgtype.Text
	TargetType    string
	TargetID      string
	Target        string
	Role          string
	ChangedFields []string
	At            time.Time
	OutboxID      pgtype.Int8
}

// The consumer's insert; a redelivered message is a no-op (ADR-0015).
func (q *Queries) StoreAuditEntry(ctx context.Context, arg StoreAuditEntryParams) error {
	_, err := q.db.Exec(ctx, storeAuditEntry,
		arg.ActorID,
		arg.ActorName,
		arg.ActorEmail,
		arg.Source,
		arg.Action,
		arg.DocumentID,
		arg.DocumentTitle,
		arg.TargetType,
		arg.TargetID,
		arg.Target,
		arg.Role,
		arg.ChangedFields,
		arg.At,
		arg.OutboxID,
	)
	return err
}
