// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (tenant_id, owner_id, title, description)
VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, owner_id, title, description, state, created_at, updated_at
`

type CreateDocumentParams struct {
	TenantID    uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.TenantID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, tenant_id, owner_id, title, description, state, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT d.id, d.tenant_id, d.owner_id, d.title, d.description, d.state, d.created_at, d.updated_at,
       count(l.id)::int AS log_count,
       coalesce(max(l.created_at), d.created_at)::timestamptz AS last_log_at
FROM documents d
LEFT JOIN logs l ON l.document_id = d.id AND NOT l.is_example
WHERE d.owner_id = $1
GROUP BY d.id
ORDER BY d.updated_at DESC
`

type ListDocumentsByOwnerRow struct {
	Document  Document
	LogCount  int32
	LastLogAt time.Time
}

// last_log_at falls back to d.created_at so the column is never NULL; it is
// meaningful only when log_count > 0. Examples are not counted.
func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListDocumentsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByOwnerRow
	for rows.Next() {
		var i ListDocumentsByOwnerRow
		if err := rows.Scan(
			&i.Document.ID,
			&i.Document.TenantID,
			&i.Document.OwnerID,
			&i.Document.Title,
			&i.Document.Description,
			&i.Document.State,
			&i.Document.CreatedAt,
			&i.Document.UpdatedAt,
			&i.LogCount,
			&i.LastLogAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET title = $2, description = $3, state = $4, updated_at = now()
WHERE id = $1 RETURNING id, tenant_id, owner_id, title, description, state, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	State       string
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.State,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
