// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (tenant_id, owner_id, title, description)
VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, owner_id, title, description, state, created_at, updated_at
`

type CreateDocumentParams struct {
	TenantID    uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.TenantID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentForUser = `-- name: GetDocumentForUser :one
SELECT d.id, d.tenant_id, d.owner_id, d.title, d.description, d.state, d.created_at, d.updated_at,
       (CASE WHEN d.owner_id = $1::uuid THEN 'owner' ELSE coalesce(g.role, '') END)::text AS role,
       (g.user_id IS NOT NULL AND g.seen_at IS NULL)::boolean AS is_new,
       coalesce(nullif(o.display_name, ''), o.email)::text AS owner_name
FROM documents d
JOIN users o ON o.id = d.owner_id
LEFT JOIN document_grants g ON g.document_id = d.id AND g.user_id = $1::uuid
WHERE d.id = $2
`

type GetDocumentForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetDocumentForUserRow struct {
	Document  Document
	Role      string
	IsNew     bool
	OwnerName string
}

// role is ” when the user neither owns nor has a grant on the document.
func (q *Queries) GetDocumentForUser(ctx context.Context, arg GetDocumentForUserParams) (GetDocumentForUserRow, error) {
	row := q.db.QueryRow(ctx, getDocumentForUser, arg.UserID, arg.ID)
	var i GetDocumentForUserRow
	err := row.Scan(
		&i.Document.ID,
		&i.Document.TenantID,
		&i.Document.OwnerID,
		&i.Document.Title,
		&i.Document.Description,
		&i.Document.State,
		&i.Document.CreatedAt,
		&i.Document.UpdatedAt,
		&i.Role,
		&i.IsNew,
		&i.OwnerName,
	)
	return i, err
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT d.id, d.tenant_id, d.owner_id, d.title, d.description, d.state, d.created_at, d.updated_at,
       count(l.id)::int AS log_count,
       coalesce(max(l.created_at), d.created_at)::timestamptz AS last_log_at
FROM documents d
LEFT JOIN logs l ON l.document_id = d.id AND NOT l.is_example
WHERE d.owner_id = $1
GROUP BY d.id
ORDER BY d.updated_at DESC
`

type ListDocumentsByOwnerRow struct {
	Document  Document
	LogCount  int32
	LastLogAt time.Time
}

// last_log_at falls back to d.created_at so the column is never NULL; it is
// meaningful only when log_count > 0. Examples are not counted.
func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListDocumentsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByOwnerRow
	for rows.Next() {
		var i ListDocumentsByOwnerRow
		if err := rows.Scan(
			&i.Document.ID,
			&i.Document.TenantID,
			&i.Document.OwnerID,
			&i.Document.Title,
			&i.Document.Description,
			&i.Document.State,
			&i.Document.CreatedAt,
			&i.Document.UpdatedAt,
			&i.LogCount,
			&i.LastLogAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedDocuments = `-- name: ListSharedDocuments :many
SELECT d.id, d.tenant_id, d.owner_id, d.title, d.description, d.state, d.created_at, d.updated_at,
       g.role,
       (g.seen_at IS NULL)::boolean AS is_new,
       coalesce(nullif(o.display_name, ''), o.email)::text AS owner_name,
       count(l.id)::int AS log_count,
       coalesce(max(l.created_at), d.created_at)::timestamptz AS last_log_at
FROM document_grants g
JOIN documents d ON d.id = g.document_id
JOIN users o ON o.id = d.owner_id
LEFT JOIN logs l ON l.document_id = d.id AND NOT l.is_example
WHERE g.user_id = $1
GROUP BY d.id, g.document_id, g.user_id, o.id
ORDER BY d.updated_at DESC
`

type ListSharedDocumentsRow struct {
	Document  Document
	Role      string
	IsNew     bool
	OwnerName string
	LogCount  int32
	LastLogAt time.Time
}

func (q *Queries) ListSharedDocuments(ctx context.Context, userID uuid.UUID) ([]ListSharedDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listSharedDocuments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedDocumentsRow
	for rows.Next() {
		var i ListSharedDocumentsRow
		if err := rows.Scan(
			&i.Document.ID,
			&i.Document.TenantID,
			&i.Document.OwnerID,
			&i.Document.Title,
			&i.Document.Description,
			&i.Document.State,
			&i.Document.CreatedAt,
			&i.Document.UpdatedAt,
			&i.Role,
			&i.IsNew,
			&i.OwnerName,
			&i.LogCount,
			&i.LastLogAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWritableDocuments = `-- name: ListWritableDocuments :many
SELECT d.id, d.tenant_id, d.owner_id, d.title, d.description, d.state, d.created_at, d.updated_at FROM documents d
LEFT JOIN document_grants g ON g.document_id = d.id AND g.user_id = $1
WHERE d.state = 'active' AND (d.owner_id = $1 OR g.role = 'editor')
ORDER BY d.updated_at DESC
`

// Active documents the user owns or edits; the bot's /docs order.
func (q *Queries) ListWritableDocuments(ctx context.Context, userID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listWritableDocuments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGrantSeen = `-- name: MarkGrantSeen :exec
UPDATE document_grants SET seen_at = now()
WHERE document_id = $1 AND user_id = $2 AND seen_at IS NULL
`

type MarkGrantSeenParams struct {
	DocumentID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) MarkGrantSeen(ctx context.Context, arg MarkGrantSeenParams) error {
	_, err := q.db.Exec(ctx, markGrantSeen, arg.DocumentID, arg.UserID)
	return err
}

const setDocumentOwner = `-- name: SetDocumentOwner :execrows
UPDATE documents SET owner_id = $1, updated_at = now() WHERE id = $2 AND owner_id = $3
`

type SetDocumentOwnerParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
	FromID  uuid.UUID
}

func (q *Queries) SetDocumentOwner(ctx context.Context, arg SetDocumentOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDocumentOwner, arg.OwnerID, arg.ID, arg.FromID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET title = $2, description = $3, state = $4, updated_at = now()
WHERE id = $1 RETURNING id, tenant_id, owner_id, title, description, state, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	State       string
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.State,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
