// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exports.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const claimExportJob = `-- name: ClaimExportJob :one
UPDATE export_jobs SET status = 'running', started_at = now()
WHERE id = (
    SELECT id FROM export_jobs
    WHERE status = 'queued' OR (status = 'running' AND started_at < now() - interval '5 minutes')
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED)
RETURNING id, tenant_id, document_id, requested_by, params, status, error, file_key, created_at, started_at, finished_at, expires_at
`

// Under app.provisioning. A running job not finished in 5 minutes had its worker die; take it again.
func (q *Queries) ClaimExportJob(ctx context.Context) (ExportJob, error) {
	row := q.db.QueryRow(ctx, claimExportJob)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.RequestedBy,
		&i.Params,
		&i.Status,
		&i.Error,
		&i.FileKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createExportJob = `-- name: CreateExportJob :one
INSERT INTO export_jobs (tenant_id, document_id, requested_by, params)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, document_id, requested_by, params, status, error, file_key, created_at, started_at, finished_at, expires_at
`

type CreateExportJobParams struct {
	TenantID    uuid.UUID
	DocumentID  uuid.UUID
	RequestedBy uuid.UUID
	Params      []byte
}

func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, createExportJob,
		arg.TenantID,
		arg.DocumentID,
		arg.RequestedBy,
		arg.Params,
	)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.RequestedBy,
		&i.Params,
		&i.Status,
		&i.Error,
		&i.FileKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExportJob = `-- name: DeleteExportJob :exec
DELETE FROM export_jobs WHERE id = $1
`

// Under app.provisioning.
func (q *Queries) DeleteExportJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExportJob, id)
	return err
}

const failExportJob = `-- name: FailExportJob :execrows
UPDATE export_jobs SET status = 'failed', error = $2, finished_at = now() WHERE id = $1 AND status = 'running'
`

type FailExportJobParams struct {
	ID    uuid.UUID
	Error string
}

func (q *Queries) FailExportJob(ctx context.Context, arg FailExportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failExportJob, arg.ID, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishExportJob = `-- name: FinishExportJob :execrows
UPDATE export_jobs
SET status = 'done', file_key = $2, error = '', finished_at = now(), expires_at = now() + interval '24 hours'
WHERE id = $1 AND status = 'running'
`

type FinishExportJobParams struct {
	ID      uuid.UUID
	FileKey string
}

// Only a running job: a reclaimed job's late finish or fail must not overwrite a newer outcome.
func (q *Queries) FinishExportJob(ctx context.Context, arg FinishExportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishExportJob, arg.ID, arg.FileKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExportJob = `-- name: GetExportJob :one
SELECT id, tenant_id, document_id, requested_by, params, status, error, file_key, created_at, started_at, finished_at, expires_at FROM export_jobs WHERE id = $1 AND document_id = $2
`

type GetExportJobParams struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
}

func (q *Queries) GetExportJob(ctx context.Context, arg GetExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJob, arg.ID, arg.DocumentID)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.RequestedBy,
		&i.Params,
		&i.Status,
		&i.Error,
		&i.FileKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getReportSettings = `-- name: GetReportSettings :one
SELECT document_id, tenant_id, goals_this_year, goals_next_year, section_map, updated_at FROM document_report_settings WHERE document_id = $1
`

func (q *Queries) GetReportSettings(ctx context.Context, documentID uuid.UUID) (DocumentReportSetting, error) {
	row := q.db.QueryRow(ctx, getReportSettings, documentID)
	var i DocumentReportSetting
	err := row.Scan(
		&i.DocumentID,
		&i.TenantID,
		&i.GoalsThisYear,
		&i.GoalsNextYear,
		&i.SectionMap,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredExportJobs = `-- name: ListExpiredExportJobs :many
SELECT id, tenant_id, document_id, requested_by, params, status, error, file_key, created_at, started_at, finished_at, expires_at FROM export_jobs WHERE expires_at <= now() ORDER BY expires_at LIMIT 100
`

// Under app.provisioning.
func (q *Queries) ListExpiredExportJobs(ctx context.Context) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExpiredExportJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportJob
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocumentID,
			&i.RequestedBy,
			&i.Params,
			&i.Status,
			&i.Error,
			&i.FileKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportJobs = `-- name: ListExportJobs :many
SELECT id, tenant_id, document_id, requested_by, params, status, error, file_key, created_at, started_at, finished_at, expires_at FROM export_jobs
WHERE document_id = $1 AND requested_by = $2 AND expires_at > now()
ORDER BY created_at DESC
LIMIT 10
`

type ListExportJobsParams struct {
	DocumentID  uuid.UUID
	RequestedBy uuid.UUID
}

// The dialog's history: the caller's live jobs on the document.
func (q *Queries) ListExportJobs(ctx context.Context, arg ListExportJobsParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobs, arg.DocumentID, arg.RequestedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportJob
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocumentID,
			&i.RequestedBy,
			&i.Params,
			&i.Status,
			&i.Error,
			&i.FileKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReportSettings = `-- name: UpsertReportSettings :exec
INSERT INTO document_report_settings (document_id, tenant_id, goals_this_year, goals_next_year, section_map)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (document_id) DO UPDATE SET
    goals_this_year = EXCLUDED.goals_this_year,
    goals_next_year = EXCLUDED.goals_next_year,
    section_map     = EXCLUDED.section_map,
    updated_at      = now()
`

type UpsertReportSettingsParams struct {
	DocumentID    uuid.UUID
	TenantID      uuid.UUID
	GoalsThisYear string
	GoalsNextYear string
	SectionMap    []byte
}

func (q *Queries) UpsertReportSettings(ctx context.Context, arg UpsertReportSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertReportSettings,
		arg.DocumentID,
		arg.TenantID,
		arg.GoalsThisYear,
		arg.GoalsNextYear,
		arg.SectionMap,
	)
	return err
}
