// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO tenant_invitations (tenant_id, email, created_by)
VALUES ($1, $2, $3) RETURNING id, tenant_id, email, created_by, created_at
`

type CreateInvitationParams struct {
	TenantID  uuid.UUID
	Email     string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation, arg.TenantID, arg.Email, arg.CreatedBy)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :execrows
DELETE FROM tenant_invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByEmail = `-- name: GetInvitationByEmail :one
SELECT id, tenant_id, email, created_by, created_at FROM tenant_invitations WHERE email = $1 ORDER BY created_at LIMIT 1
`

func (q *Queries) GetInvitationByEmail(ctx context.Context, email string) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByEmail, email)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationsByTenant = `-- name: ListInvitationsByTenant :many
SELECT id, tenant_id, email, created_by, created_at FROM tenant_invitations WHERE tenant_id = $1 ORDER BY created_at
`

func (q *Queries) ListInvitationsByTenant(ctx context.Context, tenantID uuid.UUID) ([]TenantInvitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantInvitation
	for rows.Next() {
		var i TenantInvitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
