// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (tenant_id, document_id, name, description, impact, impact_statement,
                  status, is_example, created_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $10)
RETURNING id, tenant_id, document_id, name, description, impact, impact_statement, status, is_example, created_at, created_by, updated_at, updated_by
`

type CreateLogParams struct {
	TenantID        uuid.UUID
	DocumentID      uuid.UUID
	Name            string
	Description     string
	Impact          string
	ImpactStatement pgtype.Text
	Status          string
	IsExample       bool
	CreatedAt       time.Time
	CreatedBy       uuid.UUID
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, createLog,
		arg.TenantID,
		arg.DocumentID,
		arg.Name,
		arg.Description,
		arg.Impact,
		arg.ImpactStatement,
		arg.Status,
		arg.IsExample,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.Name,
		&i.Description,
		&i.Impact,
		&i.ImpactStatement,
		&i.Status,
		&i.IsExample,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteExampleLogs = `-- name: DeleteExampleLogs :exec
DELETE FROM logs WHERE document_id = $1 AND is_example
`

func (q *Queries) DeleteExampleLogs(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExampleLogs, documentID)
	return err
}

const deleteLog = `-- name: DeleteLog :execrows
DELETE FROM logs WHERE id = $1 AND document_id = $2
`

type DeleteLogParams struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
}

func (q *Queries) DeleteLog(ctx context.Context, arg DeleteLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLog, arg.ID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLogLinks = `-- name: DeleteLogLinks :exec
DELETE FROM log_links WHERE log_id = $1
`

func (q *Queries) DeleteLogLinks(ctx context.Context, logID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLogLinks, logID)
	return err
}

const deleteLogTags = `-- name: DeleteLogTags :exec
DELETE FROM log_tags WHERE log_id = $1
`

func (q *Queries) DeleteLogTags(ctx context.Context, logID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLogTags, logID)
	return err
}

const getLog = `-- name: GetLog :one
SELECT id, tenant_id, document_id, name, description, impact, impact_statement, status, is_example, created_at, created_by, updated_at, updated_by FROM logs WHERE id = $1 AND document_id = $2
`

type GetLogParams struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
}

func (q *Queries) GetLog(ctx context.Context, arg GetLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, getLog, arg.ID, arg.DocumentID)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.Name,
		&i.Description,
		&i.Impact,
		&i.ImpactStatement,
		&i.Status,
		&i.IsExample,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertLogLink = `-- name: InsertLogLink :exec
INSERT INTO log_links (tenant_id, log_id, url, label, host, position)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLogLinkParams struct {
	TenantID uuid.UUID
	LogID    uuid.UUID
	Url      string
	Label    string
	Host     string
	Position int32
}

func (q *Queries) InsertLogLink(ctx context.Context, arg InsertLogLinkParams) error {
	_, err := q.db.Exec(ctx, insertLogLink,
		arg.TenantID,
		arg.LogID,
		arg.Url,
		arg.Label,
		arg.Host,
		arg.Position,
	)
	return err
}

const insertLogTags = `-- name: InsertLogTags :exec
INSERT INTO log_tags (tenant_id, log_id, tag_name)
SELECT $1, $2, unnest($3::text[])
`

type InsertLogTagsParams struct {
	TenantID uuid.UUID
	LogID    uuid.UUID
	Names    []string
}

func (q *Queries) InsertLogTags(ctx context.Context, arg InsertLogTagsParams) error {
	_, err := q.db.Exec(ctx, insertLogTags, arg.TenantID, arg.LogID, arg.Names)
	return err
}

const listLinksForLogs = `-- name: ListLinksForLogs :many
SELECT id, tenant_id, log_id, url, label, host, position FROM log_links WHERE log_id = ANY ($1::uuid[]) ORDER BY log_id, position
`

func (q *Queries) ListLinksForLogs(ctx context.Context, ids []uuid.UUID) ([]LogLink, error) {
	rows, err := q.db.Query(ctx, listLinksForLogs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogLink
	for rows.Next() {
		var i LogLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LogID,
			&i.Url,
			&i.Label,
			&i.Host,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogs = `-- name: ListLogs :many
SELECT l.id, l.tenant_id, l.document_id, l.name, l.description, l.impact, l.impact_statement, l.status, l.is_example, l.created_at, l.created_by, l.updated_at, l.updated_by, count(*) OVER () AS total
FROM logs l
WHERE l.document_id = $1
  AND ($2::text IS NULL
       OR l.name ILIKE '%' || $2 || '%'
       OR l.description ILIKE '%' || $2 || '%')
  AND (cardinality($3::text[]) = 0 OR l.status = ANY ($3::text[]))
  AND (cardinality($4::text[]) = 0 OR l.impact = ANY ($4::text[]))
  AND (cardinality($5::text[]) = 0 OR EXISTS (
        SELECT 1 FROM log_tags t WHERE t.log_id = l.id AND t.tag_name = ANY ($5::text[])))
  AND ($6::text IS NULL OR EXISTS (
        SELECT 1 FROM log_links k WHERE k.log_id = l.id
          AND (k.host = $6 OR k.host LIKE '%.' || $6)))
  AND ($7::timestamptz IS NULL OR l.created_at >= $7)
  AND ($8::timestamptz IS NULL OR l.created_at < $8)
ORDER BY
  CASE WHEN $9::text = 'created_at' AND NOT $10::bool THEN l.created_at END ASC,
  CASE WHEN $9::text = 'created_at' AND $10::bool THEN l.created_at END DESC,
  CASE WHEN $9::text = 'name' AND NOT $10::bool THEN lower(l.name) END ASC,
  CASE WHEN $9::text = 'name' AND $10::bool THEN lower(l.name) END DESC,
  CASE WHEN $9::text = 'impact' AND NOT $10::bool
    THEN array_position(ARRAY['low', 'medium', 'high', 'critical'], l.impact) END ASC,
  CASE WHEN $9::text = 'impact' AND $10::bool
    THEN array_position(ARRAY['low', 'medium', 'high', 'critical'], l.impact) END DESC,
  CASE WHEN $9::text = 'status' AND NOT $10::bool
    THEN array_position(ARRAY['idea', 'in_progress', 'done', 'dropped'], l.status) END ASC,
  CASE WHEN $9::text = 'status' AND $10::bool
    THEN array_position(ARRAY['idea', 'in_progress', 'done', 'dropped'], l.status) END DESC,
  l.created_at DESC, l.id
LIMIT $12::int OFFSET $11::int
`

type ListLogsParams struct {
	DocumentID uuid.UUID
	Q          pgtype.Text
	Statuses   []string
	Impacts    []string
	Tags       []string
	Host       pgtype.Text
	FromAt     pgtype.Timestamptz
	ToAt       pgtype.Timestamptz
	Sort       string
	Descending bool
	Off        int32
	Lim        int32
}

type ListLogsRow struct {
	Log   Log
	Total int64
}

// Every array parameter must be non-NULL (pass an empty array for "no filter"):
// cardinality(NULL) is NULL and would filter out every row.
func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]ListLogsRow, error) {
	rows, err := q.db.Query(ctx, listLogs,
		arg.DocumentID,
		arg.Q,
		arg.Statuses,
		arg.Impacts,
		arg.Tags,
		arg.Host,
		arg.FromAt,
		arg.ToAt,
		arg.Sort,
		arg.Descending,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogsRow
	for rows.Next() {
		var i ListLogsRow
		if err := rows.Scan(
			&i.Log.ID,
			&i.Log.TenantID,
			&i.Log.DocumentID,
			&i.Log.Name,
			&i.Log.Description,
			&i.Log.Impact,
			&i.Log.ImpactStatement,
			&i.Log.Status,
			&i.Log.IsExample,
			&i.Log.CreatedAt,
			&i.Log.CreatedBy,
			&i.Log.UpdatedAt,
			&i.Log.UpdatedBy,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT name FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForLogs = `-- name: ListTagsForLogs :many
SELECT log_id, tag_name FROM log_tags WHERE log_id = ANY ($1::uuid[]) ORDER BY tag_name
`

type ListTagsForLogsRow struct {
	LogID   uuid.UUID
	TagName string
}

func (q *Queries) ListTagsForLogs(ctx context.Context, ids []uuid.UUID) ([]ListTagsForLogsRow, error) {
	rows, err := q.db.Query(ctx, listTagsForLogs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForLogsRow
	for rows.Next() {
		var i ListTagsForLogsRow
		if err := rows.Scan(&i.LogID, &i.TagName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLog = `-- name: UpdateLog :one
UPDATE logs
SET name = $1, description = $2, impact = $3,
    impact_statement = $4, status = $5, is_example = $6,
    created_at = $7, updated_at = now(), updated_by = $8
WHERE id = $9 AND document_id = $10
RETURNING id, tenant_id, document_id, name, description, impact, impact_statement, status, is_example, created_at, created_by, updated_at, updated_by
`

type UpdateLogParams struct {
	Name            string
	Description     string
	Impact          string
	ImpactStatement pgtype.Text
	Status          string
	IsExample       bool
	CreatedAt       time.Time
	UpdatedBy       uuid.UUID
	ID              uuid.UUID
	DocumentID      uuid.UUID
}

func (q *Queries) UpdateLog(ctx context.Context, arg UpdateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, updateLog,
		arg.Name,
		arg.Description,
		arg.Impact,
		arg.ImpactStatement,
		arg.Status,
		arg.IsExample,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.DocumentID,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.Name,
		&i.Description,
		&i.Impact,
		&i.ImpactStatement,
		&i.Status,
		&i.IsExample,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertTags = `-- name: UpsertTags :exec
INSERT INTO tags (tenant_id, name)
SELECT $1, unnest($2::text[])
ON CONFLICT DO NOTHING
`

type UpsertTagsParams struct {
	TenantID uuid.UUID
	Names    []string
}

func (q *Queries) UpsertTags(ctx context.Context, arg UpsertTagsParams) error {
	_, err := q.db.Exec(ctx, upsertTags, arg.TenantID, arg.Names)
	return err
}
