// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meta.sql

package sqlcgen

import (
	"context"
)

const getMeta = `-- name: GetMeta :one
SELECT value FROM app_meta WHERE key = $1
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
