// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppMetum struct {
	Key   string
	Value string
}

type AuditEntry struct {
	ID            int64
	TenantID      uuid.UUID
	ActorID       pgtype.UUID
	ActorEmail    string
	Action        string
	DocumentID    pgtype.UUID
	DocumentTitle pgtype.Text
	Target        string
	Role          string
	At            time.Time
	ActorName     string
	Source        string
	TargetType    string
	TargetID      string
	ChangedFields []string
	OutboxID      pgtype.Int8
}

type Document struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description string
	State       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DocumentGrant struct {
	DocumentID uuid.UUID
	TenantID   uuid.UUID
	UserID     uuid.UUID
	Role       string
	GrantedBy  uuid.UUID
	GrantedAt  time.Time
	SeenAt     pgtype.Timestamptz
}

type DocumentInvitation struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	DocumentID uuid.UUID
	Email      string
	Role       string
	InvitedBy  uuid.UUID
	CreatedAt  time.Time
	AcceptedAt pgtype.Timestamptz
}

type DocumentReportSetting struct {
	DocumentID    uuid.UUID
	TenantID      uuid.UUID
	GoalsThisYear string
	GoalsNextYear string
	SectionMap    []byte
	UpdatedAt     time.Time
}

type ExportJob struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	DocumentID  uuid.UUID
	RequestedBy uuid.UUID
	Params      []byte
	Status      string
	Error       string
	FileKey     string
	CreatedAt   time.Time
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ExpiresAt   time.Time
}

type Log struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	DocumentID      uuid.UUID
	Name            string
	Description     string
	Impact          string
	ImpactStatement pgtype.Text
	Status          string
	IsExample       bool
	CreatedAt       time.Time
	CreatedBy       uuid.UUID
	UpdatedAt       time.Time
	UpdatedBy       uuid.UUID
}

type LogLink struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	LogID    uuid.UUID
	Url      string
	Label    string
	Host     string
	Position int32
}

type LogTag struct {
	TenantID uuid.UUID
	LogID    uuid.UUID
	TagName  string
}

type Outbox struct {
	ID          int64
	TenantID    uuid.UUID
	Topic       string
	Payload     []byte
	CreatedAt   time.Time
	PublishedAt pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
	Attempts    int32
}

type Tag struct {
	TenantID uuid.UUID
	Name     string
}

type TelegramLink struct {
	UserID         uuid.UUID
	TenantID       uuid.UUID
	TelegramUserID int64
	DocumentID     pgtype.UUID
	LinkedAt       time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type TenantInvitation struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Email       string
	DisplayName string
	Role        string
	CreatedAt   time.Time
}
