// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const claimOutbox = `-- name: ClaimOutbox :many
SELECT id, tenant_id, topic, payload FROM outbox
WHERE delivered_at IS NULL AND attempts < $1::int
  AND (published_at IS NULL OR published_at < now() - $2::float8 * interval '1 second')
ORDER BY id LIMIT $3 FOR UPDATE SKIP LOCKED
`

type ClaimOutboxParams struct {
	MaxAttempts   int32
	RedeliverSecs float64
	Lim           int32
}

type ClaimOutboxRow struct {
	ID       int64
	TenantID uuid.UUID
	Topic    string
	Payload  []byte
}

// Run under the provisioning flag; SKIP LOCKED lets several relays run.
// Undelivered rows are claimed again redeliver_secs after their last publish,
// until they have been published max_attempts times.
func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]ClaimOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimOutbox, arg.MaxAttempts, arg.RedeliverSecs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxRow
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueOutbox = `-- name: EnqueueOutbox :exec
INSERT INTO outbox (tenant_id, topic, payload) VALUES (app_tenant_id(), $1, $2)
`

type EnqueueOutboxParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error {
	_, err := q.db.Exec(ctx, enqueueOutbox, arg.Topic, arg.Payload)
	return err
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE outbox SET delivered_at = now() WHERE id = $1 AND delivered_at IS NULL
`

func (q *Queries) MarkOutboxDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxDelivered, id)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now(), attempts = attempts + 1 WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}

const purgeOutbox = `-- name: PurgeOutbox :exec
DELETE FROM outbox WHERE delivered_at < now() - interval '7 days'
`

// ponytail: seq-scans delivered rows; index delivered_at if the table grows.
func (q *Queries) PurgeOutbox(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOutbox)
	return err
}
