// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const claimOutbox = `-- name: ClaimOutbox :many
SELECT id, tenant_id, topic, payload FROM outbox
WHERE published_at IS NULL ORDER BY id LIMIT $1 FOR UPDATE SKIP LOCKED
`

type ClaimOutboxRow struct {
	ID       int64
	TenantID uuid.UUID
	Topic    string
	Payload  []byte
}

// Run under the provisioning flag; SKIP LOCKED lets several relays run.
func (q *Queries) ClaimOutbox(ctx context.Context, lim int32) ([]ClaimOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimOutbox, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxRow
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueOutbox = `-- name: EnqueueOutbox :exec
INSERT INTO outbox (tenant_id, topic, payload) VALUES (app_tenant_id(), $1, $2)
`

type EnqueueOutboxParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error {
	_, err := q.db.Exec(ctx, enqueueOutbox, arg.Topic, arg.Payload)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}

const purgeOutbox = `-- name: PurgeOutbox :exec
DELETE FROM outbox WHERE published_at < now() - interval '7 days'
`

func (q *Queries) PurgeOutbox(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOutbox)
	return err
}
