// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Turns every pending invitation for the email in the tenant into a grant.
	AcceptDocumentInvitations(ctx context.Context, arg AcceptDocumentInvitationsParams) ([]AcceptDocumentInvitationsRow, error)
	// Names copied into the audit message so the entry outlives the actor and the
	// document (FR-12). An id that matches nothing returns no row (ErrNotFound).
	AuditSnapshot(ctx context.Context, arg AuditSnapshotParams) (AuditSnapshotRow, error)
	// Under app.provisioning. A running job not finished in 5 minutes had its worker die; take it again.
	ClaimExportJob(ctx context.Context) (ExportJob, error)
	// Run under the provisioning flag; SKIP LOCKED lets several relays run.
	ClaimOutbox(ctx context.Context, lim int32) ([]ClaimOutboxRow, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentInvitation(ctx context.Context, arg CreateDocumentInvitationParams) (DocumentInvitation, error)
	CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error)
	// The tenant comes from the document; the composite FKs keep the user in it.
	CreateGrant(ctx context.Context, arg CreateGrantParams) (DocumentGrant, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TenantInvitation, error)
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Non-zero counts only; domain.Dashboard.Normalize fills the gaps. Months are UTC.
	DashboardBuckets(ctx context.Context, arg DashboardBucketsParams) ([]DashboardBucketsRow, error)
	// PRD-0005: examples never count. Total is all-time, the rest is [from, to).
	// impact and status literals mirror domain.Impacts and domain.Statuses; keep in sync.
	DashboardTotals(ctx context.Context, arg DashboardTotalsParams) (DashboardTotalsRow, error)
	DeleteDocument(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteExampleLogs(ctx context.Context, documentID uuid.UUID) (int64, error)
	// Under app.provisioning.
	DeleteExportJob(ctx context.Context, id uuid.UUID) error
	DeleteGrant(ctx context.Context, arg DeleteGrantParams) (int64, error)
	DeleteInvitation(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteLog(ctx context.Context, arg DeleteLogParams) (int64, error)
	DeleteLogLinks(ctx context.Context, logID uuid.UUID) error
	DeleteLogTags(ctx context.Context, logID uuid.UUID) error
	DeletePendingDocumentInvitation(ctx context.Context, arg DeletePendingDocumentInvitationParams) (int64, error)
	DeleteTelegramLink(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteTenantInvitationByEmail(ctx context.Context, arg DeleteTenantInvitationByEmailParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error
	FailExportJob(ctx context.Context, arg FailExportJobParams) (int64, error)
	// Tenant and document invitations compete; the oldest picks the tenant.
	FindOldestInvitationByEmail(ctx context.Context, email string) (FindOldestInvitationByEmailRow, error)
	// Only a running job: a reclaimed job's late finish or fail must not overwrite a newer outcome.
	FinishExportJob(ctx context.Context, arg FinishExportJobParams) (int64, error)
	// role is '' when the user neither owns nor has a grant on the document.
	GetDocumentForUser(ctx context.Context, arg GetDocumentForUserParams) (GetDocumentForUserRow, error)
	GetExportJob(ctx context.Context, arg GetExportJobParams) (ExportJob, error)
	GetLog(ctx context.Context, arg GetLogParams) (Log, error)
	GetMeta(ctx context.Context, key string) (string, error)
	GetReportSettings(ctx context.Context, documentID uuid.UUID) (DocumentReportSetting, error)
	GetTelegramLink(ctx context.Context, userID uuid.UUID) (TelegramLink, error)
	GetTelegramLinkByTelegramID(ctx context.Context, telegramUserID int64) (TelegramLink, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertLogLink(ctx context.Context, arg InsertLogLinkParams) error
	InsertLogTags(ctx context.Context, arg InsertLogTagsParams) error
	// Newest first; RLS scopes the tenant. owner_id limits to documents the user owns now (FR-6).
	// ponytail: one query with optional filters; AuditRepo.List pins a custom plan (a generic one seq-scans). Split per shape if custom plans ever miss the indexes (NFR-3).
	ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditEntry, error)
	// ponytail: DISTINCT over visible entries; cache or a summary table if pickers get slow on huge tenants.
	ListAuditActors(ctx context.Context, ownerID pgtype.UUID) ([]ListAuditActorsRow, error)
	// Latest known title per document, including deleted ones (FR-12).
	ListAuditDocuments(ctx context.Context, ownerID pgtype.UUID) ([]ListAuditDocumentsRow, error)
	// last_log_at falls back to d.created_at so the column is never NULL; it is
	// meaningful only when log_count > 0. Examples are not counted.
	ListDocumentsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListDocumentsByOwnerRow, error)
	// Under app.provisioning.
	ListExpiredExportJobs(ctx context.Context) ([]ExportJob, error)
	// The dialog's history: the caller's live jobs on the document.
	ListExportJobs(ctx context.Context, arg ListExportJobsParams) ([]ExportJob, error)
	ListGrants(ctx context.Context, documentID uuid.UUID) ([]ListGrantsRow, error)
	ListInvitationsByTenant(ctx context.Context, tenantID uuid.UUID) ([]TenantInvitation, error)
	ListLinksForLogs(ctx context.Context, ids []uuid.UUID) ([]LogLink, error)
	// Every array parameter must be non-NULL (pass an empty array for "no filter"):
	// cardinality(NULL) is NULL and would filter out every row.
	// impact and status orders mirror domain.Impacts and domain.Statuses; keep in sync.
	ListLogs(ctx context.Context, arg ListLogsParams) ([]ListLogsRow, error)
	ListPendingDocumentInvitations(ctx context.Context, documentID uuid.UUID) ([]DocumentInvitation, error)
	ListPendingDocumentInvitationsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListPendingDocumentInvitationsByTenantRow, error)
	ListSharedDocuments(ctx context.Context, userID uuid.UUID) ([]ListSharedDocumentsRow, error)
	ListTags(ctx context.Context) ([]string, error)
	ListTagsForLogs(ctx context.Context, ids []uuid.UUID) ([]ListTagsForLogsRow, error)
	ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	// Active documents the user owns or edits; the bot's /docs order.
	ListWritableDocuments(ctx context.Context, userID uuid.UUID) ([]Document, error)
	MarkGrantSeen(ctx context.Context, arg MarkGrantSeenParams) error
	MarkOutboxPublished(ctx context.Context, ids []int64) error
	// ponytail: seq-scans published rows; index published_at if the table grows.
	PurgeOutbox(ctx context.Context) error
	SetDocumentOwner(ctx context.Context, arg SetDocumentOwnerParams) (int64, error)
	SetTelegramLinkDocument(ctx context.Context, arg SetTelegramLinkDocumentParams) (int64, error)
	// The consumer's insert; a redelivered message is a no-op (ADR-0015).
	StoreAuditEntry(ctx context.Context, arg StoreAuditEntryParams) error
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateGrantRole(ctx context.Context, arg UpdateGrantRoleParams) (int64, error)
	UpdateLog(ctx context.Context, arg UpdateLogParams) (Log, error)
	UpsertReportSettings(ctx context.Context, arg UpsertReportSettingsParams) error
	UpsertTags(ctx context.Context, arg UpsertTagsParams) error
	// Re-linking the same Telegram account keeps the target document.
	UpsertTelegramLink(ctx context.Context, arg UpsertTelegramLinkParams) error
}

var _ Querier = (*Queries)(nil)
