// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sharing.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocumentInvitation = `-- name: CreateDocumentInvitation :one
INSERT INTO document_invitations (tenant_id, document_id, email, role, invited_by)
SELECT d.tenant_id, d.id, $1::text, $2::text, $3::uuid
FROM documents d WHERE d.id = $4
RETURNING id, tenant_id, document_id, email, role, invited_by, created_at, accepted_at
`

type CreateDocumentInvitationParams struct {
	Email      string
	Role       string
	InvitedBy  uuid.UUID
	DocumentID uuid.UUID
}

func (q *Queries) CreateDocumentInvitation(ctx context.Context, arg CreateDocumentInvitationParams) (DocumentInvitation, error) {
	row := q.db.QueryRow(ctx, createDocumentInvitation,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.DocumentID,
	)
	var i DocumentInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO document_grants (document_id, tenant_id, user_id, role, granted_by)
SELECT d.id, d.tenant_id, $1::uuid, $2::text, $3::uuid
FROM documents d WHERE d.id = $4
RETURNING document_id, tenant_id, user_id, role, granted_by, granted_at, seen_at
`

type CreateGrantParams struct {
	UserID     uuid.UUID
	Role       string
	GrantedBy  uuid.UUID
	DocumentID uuid.UUID
}

// The tenant comes from the document; the composite FKs keep the user in it.
func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (DocumentGrant, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.UserID,
		arg.Role,
		arg.GrantedBy,
		arg.DocumentID,
	)
	var i DocumentGrant
	err := row.Scan(
		&i.DocumentID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.SeenAt,
	)
	return i, err
}

const deleteGrant = `-- name: DeleteGrant :execrows
DELETE FROM document_grants WHERE document_id = $1 AND user_id = $2
`

type DeleteGrantParams struct {
	DocumentID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrant, arg.DocumentID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingDocumentInvitation = `-- name: DeletePendingDocumentInvitation :execrows
DELETE FROM document_invitations WHERE id = $1 AND document_id = $2 AND accepted_at IS NULL
`

type DeletePendingDocumentInvitationParams struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
}

func (q *Queries) DeletePendingDocumentInvitation(ctx context.Context, arg DeletePendingDocumentInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingDocumentInvitation, arg.ID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGrants = `-- name: ListGrants :many
SELECT g.user_id, g.role, g.granted_by, g.granted_at, u.email, u.display_name
FROM document_grants g
JOIN users u ON u.id = g.user_id
WHERE g.document_id = $1
ORDER BY g.granted_at, u.email
`

type ListGrantsRow struct {
	UserID      uuid.UUID
	Role        string
	GrantedBy   uuid.UUID
	GrantedAt   time.Time
	Email       string
	DisplayName string
}

func (q *Queries) ListGrants(ctx context.Context, documentID uuid.UUID) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsRow
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDocumentInvitations = `-- name: ListPendingDocumentInvitations :many
SELECT id, tenant_id, document_id, email, role, invited_by, created_at, accepted_at FROM document_invitations
WHERE document_id = $1 AND accepted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListPendingDocumentInvitations(ctx context.Context, documentID uuid.UUID) ([]DocumentInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingDocumentInvitations, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentInvitation
	for rows.Next() {
		var i DocumentInvitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocumentID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrantRole = `-- name: UpdateGrantRole :execrows
UPDATE document_grants SET role = $3 WHERE document_id = $1 AND user_id = $2
`

type UpdateGrantRoleParams struct {
	DocumentID uuid.UUID
	UserID     uuid.UUID
	Role       string
}

func (q *Queries) UpdateGrantRole(ctx context.Context, arg UpdateGrantRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGrantRole, arg.DocumentID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
