// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTelegramLink = `-- name: DeleteTelegramLink :exec
DELETE FROM telegram_links WHERE user_id = $1
`

func (q *Queries) DeleteTelegramLink(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTelegramLink, userID)
	return err
}

const getTelegramLink = `-- name: GetTelegramLink :one
SELECT user_id, tenant_id, telegram_user_id, document_id, linked_at FROM telegram_links WHERE user_id = $1
`

func (q *Queries) GetTelegramLink(ctx context.Context, userID uuid.UUID) (TelegramLink, error) {
	row := q.db.QueryRow(ctx, getTelegramLink, userID)
	var i TelegramLink
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.TelegramUserID,
		&i.DocumentID,
		&i.LinkedAt,
	)
	return i, err
}

const getTelegramLinkByTelegramID = `-- name: GetTelegramLinkByTelegramID :one
SELECT user_id, tenant_id, telegram_user_id, document_id, linked_at FROM telegram_links WHERE telegram_user_id = $1
`

func (q *Queries) GetTelegramLinkByTelegramID(ctx context.Context, telegramUserID int64) (TelegramLink, error) {
	row := q.db.QueryRow(ctx, getTelegramLinkByTelegramID, telegramUserID)
	var i TelegramLink
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.TelegramUserID,
		&i.DocumentID,
		&i.LinkedAt,
	)
	return i, err
}

const setTelegramLinkDocument = `-- name: SetTelegramLinkDocument :execrows
UPDATE telegram_links SET document_id = $2 WHERE user_id = $1
`

type SetTelegramLinkDocumentParams struct {
	UserID     uuid.UUID
	DocumentID pgtype.UUID
}

func (q *Queries) SetTelegramLinkDocument(ctx context.Context, arg SetTelegramLinkDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTelegramLinkDocument, arg.UserID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTelegramLink = `-- name: UpsertTelegramLink :exec
INSERT INTO telegram_links (user_id, tenant_id, telegram_user_id, linked_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    telegram_user_id = EXCLUDED.telegram_user_id,
    linked_at        = EXCLUDED.linked_at,
    document_id      = CASE WHEN telegram_links.telegram_user_id = EXCLUDED.telegram_user_id
                            THEN telegram_links.document_id END
`

type UpsertTelegramLinkParams struct {
	UserID         uuid.UUID
	TenantID       uuid.UUID
	TelegramUserID int64
	LinkedAt       time.Time
}

// Re-linking the same Telegram account keeps the target document.
func (q *Queries) UpsertTelegramLink(ctx context.Context, arg UpsertTelegramLinkParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramLink,
		arg.UserID,
		arg.TenantID,
		arg.TelegramUserID,
		arg.LinkedAt,
	)
	return err
}
