DROP TABLE IF EXISTS log_links;
DROP TABLE IF EXISTS log_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS logs;
ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_id_tenant_key;
DROP EXTENSION IF EXISTS pg_trgm;
